export let btns = [
  {
    text:'签到',
    img:'../../static/icon/sigin.png',
    show:true,
    path:'/signin'
  },
  {
    text:'会议日程',
    img:'../../static/icon/date.png',
    show:true,
    path:'/date'
  },
  {
    text:'图文直播',
    img:'../../static/icon/liveing.png',
    show:true,
    path:'/living'
  },
  {
    text:'旅游交易会',
    img:'../../static/icon/meeting.png',
    show:true,
    path:'/trademeet'
  },
  {
    text:'智慧地图',
    img:'../../static/icon/map.png',
    show:true,
    path:'/map'
  },
  {
    text:'景区导览',
    img:'../../static/icon/dh.png',
    show:true,
    path:'/dh'
  },
  {
    text:'留言板',
    img:'../../static/icon/msg.png',
    show:true,
    path:'/msg'
  },
  {
    text:'名片夹',
    img:'../../static/icon/card.png',
    show:true,
    path:''
  },
  {
    text:'个人中心',
    img:'../../static/icon/pc.png',
    show:true,
    path:'individualcenter'
  }
]
  
